### ISSUE TITLE
Update to Vert.x 5?

### ISSUE THREAD

**Issue by tsegismont** [vertx-howtos/graal-native-image-howto#18]
Currently there is no public metadata for Netty 4.2.

Until it is contributed, the best option is to run the application with the GraalVM agent to dump metadata before create the native image.

This is more or less what is explained in https://graalvm.github.io/native-build-tools/latest/maven-plugin-quickstart.html
And I'm not sure there is much value in reproducing this how-to with Vert.x (because there's nothing specific to Vert.x)

For the record, I tried building a `native-image` with the help of the agent, and it worked.

**Comment by UkonnRa** [comment]
Same issue, I met something like:

```
 error LNK2001: unresolved external symbol Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0
C:\Workspaces\vertx-test\build\native\nativeCompile\vertx-test.exe : fatal error LNK1120: 1 unresolved externals
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:202)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:118)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:742)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:551)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

But everything works fine when downgrade to Vertx 4.
