### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by sstubbs** [vertx-howtos/graal-native-image-howto#3]
Do you have any working examples of clustering? I've tried with all three embedded versions hazelcast, infinispan and ignite with no luck.

**Comment by sstubbs** [comment]
I've now also tried zookeeper and am also having problems with that.

**Comment by pmlopes** [comment]
I'm not aware of zookeeper being able to build as native, once it happens (or any other cluster engine) we can update the project.

**Comment by sstubbs** [comment]
Here is the issue for for hazelcast. https://github.com/oracle/graal/issues/1508

**Comment by sheldon-markk** [comment]
Was testing this on a simple vertx cluster application. Got the same issue and it was resolved using
 
`    -H:-UseServiceLoaderFeature `

But when i run the application i get the following errors

`Exception in thread "main" java.util.ServiceConfigurationError: io.vertx.core.spi.launcher.CommandFactory: Provider io.vertx.core.impl.launcher.commands.RunCommandFactory not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.vertx.core.ServiceHelper.loadFactories(ServiceHelper.java:55)
	at io.vertx.core.impl.launcher.ServiceCommandFactoryLoader.<init>(ServiceCommandFactoryLoader.java:36)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.<init>(VertxCommandLauncher.java:98)
	at io.vertx.core.Launcher.<init>(Launcher.java:37)
	at com.cluster.subscriber.Application.<init>(Application.java:15)
	at com.cluster.subscriber.Application.main(Application.java:20)`
