### ISSUE TITLE
Error with graal 19.3.0

### ISSUE THREAD

**Issue by sstubbs** [vertx-howtos/graal-native-image-howto#4]
Hi,

I'm getting an error when trying this on graal 19.3.0

Looks like a netty issue but would like to confirm that it's not a vertx issue if possible before creating an issue there. 19.2.1 works fine so I will just continue to use that but it would be nice to get the perfomance enhancements of 19.3.0 at some point.

Here is the error

```
Warning: Aborting stand-alone image build. Unsupported features in 4 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace:  object io.netty.channel.socket.InternetProtocolFamily
        method io.netty.resolver.dns.DnsNameResolver.preferredAddressType(ResolvedAddressTypes)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.preferredAddressType(ResolvedAddressTypes): 
        at io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:479)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:437)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:475)
        at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:186)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:93)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:78)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:164)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:141)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace:  object java.net.InetSocketAddress$InetSocketAddressHolder
        object java.net.InetSocketAddress
        object io.netty.resolver.dns.SingletonDnsServerAddresses
        method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses()
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(): 
        at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:141)
        at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:91)
        at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:39)
        at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:75)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:167)
        at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
        at io.vertx.core.Vertx.vertx(Vertx.java:85)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:378)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.vertx.core.Launcher.main(Launcher.java:45)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
        at parsing io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:657)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(String): 
        at io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:649)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:984)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:959)
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96)
        at com.oracle.svm.reflect.InflightNameResolver_resolve_83c4421189a07f3b0e2b4decf5b58356cabb2642_109.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:736)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:719)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:339)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
        at parsing io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:111)
Call path from entry point to io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(InetSocketAddress): 
        at io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:96)
        at io.netty.resolver.dns.DnsQueryContextManager.add(DnsQueryContextManager.java:42)
        at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:69)
        at io.netty.resolver.dns.TcpDnsQueryContext.<init>(TcpDnsQueryContext.java:35)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$2.operationComplete(DnsNameResolver.java:1293)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$2.operationComplete(DnsNameResolver.java:1283)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.access$300(DefaultPromise.java:35)
        at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:531)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

**Comment by pmlopes** [comment]
I'll look at it, thanks for the heads up.

**Comment by BornToRain** [comment]
Is it settled now? I had the same problem

**Comment by hugomarcelino-spotqa** [comment]
Getting the same error. Any news regarding this issue?

**Comment by pmlopes** [comment]
There's an workaround on the issue filled on graalvm repo. But they wrote that it should be solved on the next release. It has been applied here https://github.com/vertx-howtos/graal-native-image-howto/commit/b5933aa37c98a599c16c57de7f03d05023bba2f8

But I'm afraid it's not enough

**Comment by pmlopes** [comment]
howto updated to work with 20.3.0
